#!/bin/bash

# @Name: dumpDb
# @Desc: 导出数据库数据和结构
# @Author: KuangHeng
# Date: 2019.04.01

# Features:
# 1.导出文件名称包含当前日期
# 2.删除七天前的文件

# mysqldump -h localhost -uroot -proot --databases db1 > /home/sql/

echo -e "\e[2mInput the hostName:\e[0m"
read hostName

echo -e "\e[2mInput the DB username:\e[0m"
reade userName
