#!/bin/bash

md_title="# "
md_createtime="*创建时间:"`date "+%F %H:%M:%S"`"*\n"
md_updatetime="***更新时间:"`date "+%F %H:%M:%S"`"***\n"
md_toc="\n[TOC]\n"

echo '请输入文件名称:'
read md_name    # read读取用户输入并赋值给变量

md_init_str=$md_title$md_name"\n"$md_createtime$md_updatetime$md_toc
md_file=$md_name'.md'
touch '/home/hikwang/Documents/evernote/kh-summary/'$md_file
echo -e $md_init_str > $md_file
export DISPLAY=:0 && remarkable $md_file > /dev/null &
