#!/bin/bash

echo '文章标题'
read title

echo '文章副标题'
read subtitle

echo '分类'
read categories

echo '背景图（默认：circuitBoard）'
read pat

echo '标签（以空格分隔）'
read tags

date=`date +%F`

headerStr="---\nlayout: post\ntitle: $title\nsubtitle: $subtitle\ndate: $date\ncategories: $categories\npostPatterns: $pat\ntags: $tags\n---"

postName=$date'-'$title'.md'

postPath='/home/hikwang/www/hikwang.github.io/_posts/'

touch $postPath$postName

echo -e $headerStr > $postPath$postName
